import { Routes } from '@angular/router';
import { LandingHeroComponent } from './landing-hero/landing-hero.component';
import { ProduktlisteComponent } from './produktliste/produktliste.component';
import { DatenschutzComponent } from './datenschutz/datenschutz.component';
import { ContactinformationComponent } from './contactinformation/contactinformation.component';
import { RefundPolicyComponent } from './refund-policy/refund-policy.component';
import { AGBComponent } from './agb/agb.component';
import { ImpressumComponent } from './impressum/impressum.component';
import { VersandComponent } from './versand/versand.component';
import { ContactComponent } from './contact/contact.component';
import { BasketComponent } from './basket/basket.component';
import { RegistrationComponent } from './registration/registration.component';
import { LoginComponent } from './login/login.component';
import { ForgotpasswordComponent } from './forgotpassword/forgotpassword.component';
import { ResetpasswordComponent } from './resetpassword/resetpassword.component';

export const routes: Routes = [
  { path: '', component: LandingHeroComponent },
  { path: 'products', component: ProduktlisteComponent },
  { path: 'datenschutz', component: DatenschutzComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'contactinfos', component: ContactinformationComponent },
  { path: 'refund-policy', component: RefundPolicyComponent },
  { path: 'AGB', component: AGBComponent },
  { path: 'impressum', component: ImpressumComponent },
  { path: 'versand', component: VersandComponent },
  { path: 'basket', component: BasketComponent },
  { path: 'registration', component: RegistrationComponent },
  { path: 'login', component: LoginComponent },
  { path: 'forgotpassword', component: ForgotpasswordComponent },
  { path: 'resetpassword', component: ResetpasswordComponent },
 ];
